
```{r setup, include=FALSE, warning=F, message=F}
packages <- c("here", "tidyverse", "knitr", "kableExtra")

for (package in packages) {
  if (!require(package, character.only = T, quietly = T)) {
    install.packages(package, repos = "http://lib.stat.cmu.edu/R/CRAN")
  }
}

for (package in packages) {
  library(package, character.only = T)
}
```

# Speed Testing

This repo is a work in progress. Contains code I use to speed test functions on different computers.

```{r, echo=F, warning=F, message=F}

mbm1 <- readRDS(file = here("data","speed_benchmark.rds"))

mbm1 <- as_tibble(mbm1) %>%
  rename(Test=expr) %>% 
  group_by(Test) %>%
  summarize(Min = min(time)/1e9,
            Mean = mean(time)/1e9,
            Median = median(time)/1e9,
            Max = max(time)/1e9,
            N = n())
```

---

<br><br><br><br>

### Test on 2020 MBP M1, 16 GB RAM
```{r, echo=F, warning=F, message=F}
knitr::kable(mbm1, 
             digits = 2, 
             align = "lccccc",
             "pipe")
```

